api:
  image: tomruttle/piglatin-api
  ports:
    - "3000:3000"

fe:
  image: tomruttle/piglatin-fe
  ports:
    - "80:80"
  links:
    - api
  volumes:
    - /home/truttle/Documents/personal/src/piglatin-fe:/app
  environment:
    - API_ADDR=http://api:3000

